#!/bin/bash

mysql --user=root --password="$MYSQL_ROOT_PASSWORD" <<-EOSQL
    CREATE DATABASE IF NOT EXISTS $MYSQL_TESTING_DATABASE;
    GRANT ALL PRIVILEGES ON \`$MYSQL_TESTING_DATABASE%\`.* TO '$MYSQL_USER'@'%';
EOSQL
