# Can be override by env variable 'COMPOSE_PROJECT_NAME'
name: laravel
volumes:
  mysql-data:
services:
  app:
    build:
      context: app
      dockerfile: Dockerfile
      args:
        - CONTAINER_USER=${CONTAINER_USER:-laravel}
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - ${VITE_PORT:-5173}:${VITE_PORT:-5173}
    volumes:
      - ${SOURCE_PATH:-../..}:/var/www/html
    depends_on:
      - mysql
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - ${FORWARD_APP_PORT:-80}:80
    volumes:
      - ${SOURCE_PATH:-../..}:/var/www/html
    depends_on:
      - app
  mysql:
    image: mysql:8.0.32
    ports:
      - ${FORWARD_MYSQL_PORT:-3306}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
      - MYSQL_USER=${MYSQL_USER:-laravel}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-laravel}
      - MYSQL_TESTING_DATABASE=${MYSQL_TESTING_DATABASE:-laravel_testing}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/init/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh
  mailhog:
    image: mailhog/mailhog
    ports:
      - ${FORWARD_MAILHOG_SMTP_PORT:-1025}:1025 # smtp server
      - ${FORWARD_MAILHOG_HTTP_PORT:-8025}:8025 # web ui
