name: Tests

on:
  pull_request

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@2.32.0
        with:
          php-version: '8.2'
          tools: composer:v2

      - name: Install Dependencies
        run: composer install -q --no-interactions

      - name: Run Tests
        run: ./vendor/bin/phpunit